# Build ASP.NET Core project using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core?view=vsts

# define the VM image I want to use for my build
pool:
  vmImage: 'Ubuntu 16.04'

# define variables to use during the build
variables:
  projectFile: 'src/dotnet/AzureDevopsExamples.React.csproj'
  buildConfiguration: 'Release'

# specific path build
trigger:
  paths:
    include:
    - src/dotnet/*
    - dotnet-pipeline.yml

# define the steps of the build
steps:

## Run the dotnet build/publish
- script: |
    dotnet build $(projectFile) --configuration $(buildConfiguration)
    dotnet publish $(projectFile) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)

## Archive the files into a zip file for publishing
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(Build.ArtifactStagingDirectory)
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    includeRootFolder: false

## Publish the zip file
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'